import type { GroupSpec, ProjectConfig } from './types';

export const DEFAULT_CONFIG: ProjectConfig = {
  // Group 0: Project Info
  project_description: '',

  // Group 1: Saccade Detection
  saccade_min_velocity: 30,
  saccade_max_velocity: 1000,
  saccade_min_duration: 10,
  saccade_max_duration: 150,
  saccade_min_amplitude: 0.5,
  saccade_max_amplitude: 45,
  saccade_refractory_period: 50,
  saccade_inter_saccadic_interval: 50,
  saccade_max_gap_for_velocity: 25,
  saccade_direction_filter_enabled: false,
  saccade_direction_filter_angle: 0,
  saccade_direction_filter_tolerance: 30,

  // Group 2: Fixation Detection
  fixation_min_duration: 100,
  fixation_max_dispersion: 1.0,
  fixation_algorithm: 'I-VT',

  // Group 3: Pupillometry
  pupil_baseline_window: 200,
  pupil_baseline_correction_method: 'subtraction',
  pupil_blink_interpolation_method: 'linear',
  pupil_blink_max_gap: 150,
  pupil_min_diameter: 1.5,
  pupil_max_diameter: 9.0,
  pupil_lr_asymmetry_tolerance: 0.5,

  // Group 4: Gaze Quality & Data Integrity
  quality_min_valid_frame_ratio: 75,
  quality_max_consecutive_invalid: 10,
  quality_eye_openness_threshold: 0.5,

  // Group 5: Epoch / Event-Locking
  epoch_pre_stimulus_window: 500,
  epoch_post_stimulus_window: 1500,
  epoch_artifact_sd_threshold: 3.0,
  epoch_artifact_max_ratio: 20,

  // Group 6: Focus & Vergence
  focus_min_distance: 0.2,
  focus_max_distance: 10.0,
  focus_min_stability: 0.3,
};

export const STATUS_MESSAGES = {
  new: 'Please enter project configuration for this project...',
  dirty: 'The project config has unsaved changes, please save before closing.',
  clean: 'Project config saved successfully.',
};

export const GROUPS: GroupSpec[] = [
  {
    id: 'info',
    title: 'Project Info',
    fields: [
      {
        type: 'text-area',
        key: 'project_description',
        label: 'Project Description',
        default: '',
        maxLength: 500,
        rows: 4,
        placeholder: 'Briefly describe this project — purpose, stimulus, population, etc.',
      },
    ],
  },
  {
    id: 'saccade',
    title: 'Saccade Detection',
    fields: [
      {
        type: 'range-slider',
        key: 'saccade_min_velocity',
        label: 'Saccade Min Velocity',
        units: 'deg/s',
        default: 30,
        min: 10,
        max: 300,
        step: 1,
      },
      {
        type: 'number-input',
        key: 'saccade_max_velocity',
        label: 'Saccade Max Velocity',
        units: 'deg/s',
        default: 1000,
        min: 200,
        max: 2000,
        step: 10,
      },
      {
        type: 'range-pair',
        label: 'Saccade Duration',
        units: 'ms',
        minKey: 'saccade_min_duration',
        maxKey: 'saccade_max_duration',
        minBounds: { min: 5, max: 50 },
        maxBounds: { min: 50, max: 500 },
        step: 1,
      },
      {
        type: 'range-pair',
        label: 'Saccade Amplitude',
        units: 'deg',
        minKey: 'saccade_min_amplitude',
        maxKey: 'saccade_max_amplitude',
        minBounds: { min: 0.1, max: 10 },
        maxBounds: { min: 10, max: 90 },
        step: 0.1,
        decimals: 1,
      },
      {
        type: 'range-slider',
        key: 'saccade_refractory_period',
        label: 'Refractory Period',
        units: 'ms',
        default: 50,
        min: 20,
        max: 200,
        step: 1,
      },
      {
        type: 'range-slider',
        key: 'saccade_inter_saccadic_interval',
        label: 'Inter-Saccadic Interval',
        units: 'ms',
        default: 50,
        min: 20,
        max: 300,
        step: 1,
      },
      {
        type: 'number-input',
        key: 'saccade_max_gap_for_velocity',
        label: 'Max Gap for Velocity',
        units: 'ms',
        default: 25,
        min: 5,
        max: 100,
        step: 1,
      },
      {
        type: 'toggle-switch',
        key: 'saccade_direction_filter_enabled',
        label: 'Direction Filter',
        default: false,
      },
      {
        type: 'range-slider',
        key: 'saccade_direction_filter_angle',
        label: 'Direction Filter Angle',
        units: 'deg',
        default: 0,
        min: 0,
        max: 360,
        step: 1,
        dependsOn: { key: 'saccade_direction_filter_enabled', equals: true, mode: 'hidden' },
      },
      {
        type: 'range-slider',
        key: 'saccade_direction_filter_tolerance',
        label: 'Direction Filter Tolerance',
        units: 'deg',
        default: 30,
        min: 5,
        max: 90,
        step: 1,
        dependsOn: { key: 'saccade_direction_filter_enabled', equals: true, mode: 'hidden' },
      },
    ],
  },
  {
    id: 'fixation',
    title: 'Fixation Detection',
    fields: [
      {
        type: 'range-slider',
        key: 'fixation_min_duration',
        label: 'Fixation Min Duration',
        units: 'ms',
        default: 100,
        min: 50,
        max: 300,
        step: 1,
      },
      {
        type: 'radio-group',
        key: 'fixation_algorithm',
        label: 'Fixation Algorithm',
        default: 'I-VT',
        options: [
          { value: 'I-VT', label: 'I-VT (velocity threshold)' },
          { value: 'I-DT', label: 'I-DT (dispersion threshold)' },
        ],
      },
      {
        type: 'range-slider',
        key: 'fixation_max_dispersion',
        label: 'Max Dispersion',
        units: 'deg',
        default: 1.0,
        min: 0.3,
        max: 3.0,
        step: 0.1,
        decimals: 1,
        dependsOn: { key: 'fixation_algorithm', equals: 'I-DT', mode: 'dimmed' },
      },
    ],
  },
  {
    id: 'pupillometry',
    title: 'Pupillometry',
    fields: [
      {
        type: 'number-input',
        key: 'pupil_baseline_window',
        label: 'Baseline Window',
        units: 'ms',
        default: 200,
        min: 100,
        max: 1000,
        step: 50,
      },
      {
        type: 'radio-group',
        key: 'pupil_baseline_correction_method',
        label: 'Baseline Correction Method',
        default: 'subtraction',
        options: [
          { value: 'subtraction', label: 'Subtraction' },
          { value: 'percent_change', label: 'Percent Change' },
          { value: 'z_score', label: 'Z-Score' },
        ],
      },
      {
        type: 'radio-group',
        key: 'pupil_blink_interpolation_method',
        label: 'Blink Interpolation Method',
        default: 'linear',
        options: [
          { value: 'linear', label: 'Linear' },
          { value: 'cubic_spline', label: 'Cubic Spline' },
          { value: 'none', label: 'None' },
        ],
      },
      {
        type: 'range-slider',
        key: 'pupil_blink_max_gap',
        label: 'Blink Max Gap',
        units: 'ms',
        default: 150,
        min: 50,
        max: 500,
        step: 1,
        dependsOn: { key: 'pupil_blink_interpolation_method', equals: 'none', mode: 'dimmed' },
      },
      {
        type: 'range-pair',
        label: 'Pupil Diameter',
        units: 'mm',
        minKey: 'pupil_min_diameter',
        maxKey: 'pupil_max_diameter',
        minBounds: { min: 1.0, max: 3.0 },
        maxBounds: { min: 6.0, max: 12.0 },
        step: 0.1,
        decimals: 1,
      },
      {
        type: 'range-slider',
        key: 'pupil_lr_asymmetry_tolerance',
        label: 'L/R Asymmetry Tolerance',
        units: 'mm',
        default: 0.5,
        min: 0.1,
        max: 2.0,
        step: 0.1,
        decimals: 1,
      },
    ],
  },
  {
    id: 'quality',
    title: 'Gaze Quality & Data Integrity',
    fields: [
      {
        type: 'range-slider',
        key: 'quality_min_valid_frame_ratio',
        label: 'Min Valid Frame Ratio',
        units: '%',
        default: 75,
        min: 50,
        max: 100,
        step: 1,
      },
      {
        type: 'number-input',
        key: 'quality_max_consecutive_invalid',
        label: 'Max Consecutive Invalid',
        units: 'frames',
        default: 10,
        min: 3,
        max: 50,
        step: 1,
      },
      {
        type: 'range-slider',
        key: 'quality_eye_openness_threshold',
        label: 'Eye Openness Threshold',
        units: 'ratio',
        default: 0.5,
        min: 0.1,
        max: 0.9,
        step: 0.01,
        decimals: 2,
      },
    ],
  },
  {
    id: 'epoch',
    title: 'Epoch / Event-Locking',
    fields: [
      {
        type: 'number-input',
        key: 'epoch_pre_stimulus_window',
        label: 'Pre-Stimulus Window',
        units: 'ms',
        default: 500,
        min: 100,
        max: 2000,
        step: 50,
      },
      {
        type: 'number-input',
        key: 'epoch_post_stimulus_window',
        label: 'Post-Stimulus Window',
        units: 'ms',
        default: 1500,
        min: 200,
        max: 5000,
        step: 50,
      },
      {
        type: 'range-slider',
        key: 'epoch_artifact_sd_threshold',
        label: 'Artifact SD Threshold',
        units: 'SD',
        default: 3.0,
        min: 2.0,
        max: 5.0,
        step: 0.1,
        decimals: 1,
      },
      {
        type: 'range-slider',
        key: 'epoch_artifact_max_ratio',
        label: 'Artifact Max Ratio',
        units: '%',
        default: 20,
        min: 5,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: 'focus',
    title: 'Focus & Vergence',
    fields: [
      {
        type: 'range-pair',
        label: 'Focus Distance',
        units: 'm',
        minKey: 'focus_min_distance',
        maxKey: 'focus_max_distance',
        minBounds: { min: 0.1, max: 1.0 },
        maxBounds: { min: 2.0, max: 100.0 },
        step: 0.1,
        decimals: 1,
      },
      {
        type: 'range-slider',
        key: 'focus_min_stability',
        label: 'Min Stability',
        units: 'ratio',
        default: 0.3,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        decimals: 2,
      },
    ],
  },
];
